unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a

set -g mouse on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
gray_darker="#292c3c"
green_soft="#81c8be"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"
standout="#303446"

set-option -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_darker}, bg=${green_soft}"
set -g mode-style "fg=${gray_dark}, bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"
set -g status-right " %H:%M | 󰃭 %Y-%m-%d"
set -g status-left "#[nobold][#S]: #[nobold]"
set -g window-status-current-format " (#I:#W)"
set -g window-status-format "  #I:#W "


set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'